version: '3.8'

services:
  db:
    image: postgres:15
    container_name: calibre_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: calibredb
    ports:
      - "5433:5432"
    volumes:
      - calibre_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: calibre_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@calibre.io
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - db

volumes:
  calibre_pgdata:
